spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/testdb
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: *