# base/hpa.yml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: springboot-hpa
  namespace: springboot-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: springboot-app
  minReplicas: 2  # 최소 파드 수
  maxReplicas: 10  # 최대 파드 수
  metrics:  # 스케일링 메트릭 설정
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70  # CPU 사용률 70% 초과시 스케일 아웃
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80  # 메모리 사용률 80% 초과시 스케일 아웃
  behavior:  # 스케일링 동작 설정
    scaleDown:
      stabilizationWindowSeconds: 300  # 스케일 다운 전 대기 시간
      policies:
        - type: Pods
          value: 1  # 한 번에 제거할 파드 수
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0  # 즉시 스케일 업
      policies:
        - type: Pods
          value: 2  # 한 번에 추가할 파드 수
          periodSeconds: 30
