# base/secrets.yml
apiVersion: v1
kind: Secret
metadata:
  name: springboot-secrets
  namespace: springboot-app
type: Opaque
data:
  # base64로 인코딩된 민감 정보
  DATABASE_USERNAME: base64encodedusername
  DATABASE_PASSWORD: base64encodedpassword