# overlays/prod/deployment-patch.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
spec:
  template:
    spec:
      containers:
        - name: springboot-app
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"