# overlays/prod/secrets-patch.yml
apiVersion: v1
kind: Secret
metadata:
  name: springboot-secrets
type: Opaque
data:  # 운영 환경에서는 base64로 인코딩된 값 사용
  DATABASE_USERNAME: "cHJvZF91c2Vy"  # prod_user in base64
  DATABASE_PASSWORD: "cHJvZF9wYXNzd29yZA=="  # prod_password in base64
  JWT_SECRET: "cHJvZF9qd3Rfc2VjcmV0X2tleV9taW5pbXVtXzMyX2NoYXJhY3RlcnNfbG9uZw=="  # prod jwt secret in base64
