# overlays/dev/secrets-patch.yml
apiVersion: v1
kind: Secret
metadata:
  name: springboot-secrets
type: Opaque
stringData:  # 개발 환경에서는 직접 값을 볼 수 있도록 stringData 사용
  DATABASE_USERNAME: "dev_user"
  DATABASE_PASSWORD: "dev_password"
  JWT_SECRET: "dev_jwt_secret_key_minimum_32_characters_long"